/**
 * Emit visual.spec.mjs implementing the plan §7 stabilization sequence
 * (steps 1-13) for every route in payload.json, once per Playwright project.
 * Failures are thrown as 'VR:<CODE> route=<route> project=<project>
 * detail=...' so the runner can map them to stable error codes.
 *
 * @param playwrightImportUrl file:// URL of the toolkit's own
 *   @playwright/test ESM entry; the temp dir has no node_modules, so the
 *   generated spec must import by absolute URL.
 */
export function generateVisualSpec(playwrightImportUrl: string): string {
  return `// Generated by @thisdot/visual-regression - do not edit.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from ${JSON.stringify(playwrightImportUrl)};

const payload = JSON.parse(readFileSync(new URL('./payload.json', import.meta.url), 'utf8'));
const serverOrigin = new URL(payload.origin).origin;

const tagged = (code, route, project, detail) =>
  new Error('VR:' + code + ' route=' + route + ' project=' + project + ' detail=' + detail);

const isAllowedRequest = (url) => {
  if (payload.network.allowAll) return true;
  if (url.startsWith('data:') || url.startsWith('blob:')) return true;
  try {
    return payload.network.allowedOrigins.includes(new URL(url).origin);
  } catch {
    return false;
  }
};

async function bounded(promise, ms, makeError) {
  let timer;
  try {
    return await Promise.race([
      promise,
      new Promise((_resolve, reject) => {
        timer = setTimeout(() => reject(makeError()), ms);
      }),
    ]);
  } finally {
    clearTimeout(timer);
  }
}

// Steps 5 and 12: document.fonts.ready plus each configured font probe.
async function awaitFonts(page, route, project) {
  await bounded(
    page.evaluate(() => document.fonts.ready.then(() => undefined)),
    payload.timeouts.stepMs,
    () => tagged('FONT_CHECK_FAILED', route, project, 'document.fonts.ready timed out'),
  );
  for (const family of payload.capture.fontChecks) {
    const available = await bounded(
      page.evaluate((name) => document.fonts.check('16px ' + name), family),
      payload.timeouts.stepMs,
      () => tagged('FONT_CHECK_FAILED', route, project, 'font check timed out family=' + family),
    );
    if (!available) {
      throw tagged('FONT_CHECK_FAILED', route, project, 'family=' + family);
    }
  }
}

// Steps 9 and 12: decode images and collect broken required resources. Only
// images whose currentSrc resolves same-origin or to an allowed origin are
// required; images blocked by the external-request policy never count.
async function assertRequiredImages(page, route, project) {
  const broken = await bounded(
    page.evaluate(async (network) => {
      const isRequired = (src) => {
        if (network.allowAll) return true;
        try {
          return network.allowedOrigins.includes(new URL(src, window.location.href).origin);
        } catch {
          return false;
        }
      };
      const images = Array.from(document.images);
      await Promise.all(
        images.map((image) =>
          typeof image.decode === 'function' ? image.decode().catch(() => undefined) : undefined,
        ),
      );
      return images
        .filter(
          (image) =>
            image.currentSrc !== '' && image.naturalWidth === 0 && isRequired(image.currentSrc),
        )
        .map((image) => image.currentSrc);
    }, payload.network),
    payload.timeouts.stepMs,
    () => tagged('RESOURCE_BROKEN', route, project, 'image decode timed out'),
  );
  if (broken.length > 0) {
    throw tagged('RESOURCE_BROKEN', route, project, 'srcs=' + broken.slice(0, 10).join(','));
  }
}

for (const route of payload.routes) {
  // Step 1: Playwright gives each test a clean context with the configured
  // locale, timezone, color scheme, viewport, and reduced motion.
  test('visual ' + route.route, async ({ page }, testInfo) => {
    const project = testInfo.project.name;

    // Step 2: abort every request that is not same-origin, data:, blob:, or
    // explicitly allowed (service workers are blocked by the config).
    await page.route('**/*', (intercepted) =>
      isAllowedRequest(intercepted.request().url()) ? intercepted.continue() : intercepted.abort(),
    );

    // Step 3: navigate and require a successful response.
    let response = null;
    try {
      response = await page.goto(serverOrigin + route.route, {
        waitUntil: 'domcontentloaded',
        timeout: payload.timeouts.navigationMs,
      });
    } catch (error) {
      throw tagged(
        'NAVIGATION_FAILED',
        route.route,
        project,
        error instanceof Error ? error.message : String(error),
      );
    }
    if (response === null || !response.ok()) {
      throw tagged(
        'NAVIGATION_FAILED',
        route.route,
        project,
        'status=' + (response === null ? 'no-response' : String(response.status())),
      );
    }

    // Step 4: every configured readiness selector must become visible.
    for (const selector of payload.capture.readinessSelectors) {
      try {
        await page
          .locator(selector)
          .first()
          .waitFor({ state: 'visible', timeout: payload.timeouts.readinessMs });
      } catch {
        throw tagged('READINESS_TIMEOUT', route.route, project, 'selector=' + selector);
      }
    }

    // Step 5: fonts ready plus configured font probes.
    await awaitFonts(page, route.route, project);

    // Step 6: freeze animations, transitions, and carets; pin emulated media.
    await page.addStyleTag({
      content:
        '*, *::before, *::after { animation: none !important; transition: none !important; caret-color: transparent !important; } html { scroll-behavior: auto !important; }',
    });
    await page.emulateMedia({
      colorScheme: payload.capture.colorScheme,
      reducedMotion: payload.capture.reducedMotion,
    });

    // Step 7: make lazy images eager.
    await page.evaluate(() => {
      for (const image of Array.from(document.querySelectorAll('img[loading="lazy"]'))) {
        image.loading = 'eager';
      }
    });

    // Step 8: scroll through the full document height in viewport-sized
    // steps, one animation frame per step, to trigger lazy rendering.
    await bounded(
      page.evaluate(async () => {
        const nextFrame = () =>
          new Promise((resolve) => requestAnimationFrame(() => resolve(undefined)));
        const stepSize = Math.max(1, window.innerHeight);
        let offset = 0;
        while (offset < document.documentElement.scrollHeight) {
          window.scrollTo(0, offset);
          await nextFrame();
          offset += stepSize;
        }
        window.scrollTo(0, document.documentElement.scrollHeight);
        await nextFrame();
      }),
      payload.timeouts.stepMs,
      () => tagged('CAPTURE_FAILED', route.route, project, 'incremental scroll timed out'),
    );

    // Step 9: decode images and fail on broken required resources.
    await assertRequiredImages(page, route.route, project);

    // Step 10: stabilize videos on a deterministic frame, preferring posters.
    await page.evaluate(() => {
      for (const video of Array.from(document.querySelectorAll('video'))) {
        video.autoplay = false;
        video.muted = true;
        try {
          video.pause();
        } catch {
          /* not playable */
        }
        try {
          video.currentTime = 0;
        } catch {
          /* no seekable media */
        }
        if (video.getAttribute('poster') !== null) {
          video.preload = 'none';
          try {
            video.load();
          } catch {
            /* keep current frame */
          }
        }
      }
    });

    // Step 11: back to the top, then two animation frames.
    await bounded(
      page.evaluate(async () => {
        window.scrollTo(0, 0);
        await new Promise((resolve) =>
          requestAnimationFrame(() => requestAnimationFrame(() => resolve(undefined))),
        );
      }),
      payload.timeouts.stepMs,
      () => tagged('CAPTURE_FAILED', route.route, project, 'scroll-to-top settle timed out'),
    );

    // Step 12: lazy content may have added fonts and images; re-check both.
    await awaitFonts(page, route.route, project);
    await assertRequiredImages(page, route.route, project);

    // Step 13: exactly one screenshot.
    try {
      await page.screenshot({
        fullPage: payload.capture.fullPage,
        path: join(payload.screenshotsDir, project, route.screenshotName),
        animations: 'disabled',
        caret: 'hide',
        scale: 'css',
        mask: payload.capture.masks.map((selector) => page.locator(selector)),
        timeout: payload.timeouts.screenshotMs,
      });
    } catch (error) {
      throw tagged(
        'CAPTURE_FAILED',
        route.route,
        project,
        error instanceof Error ? error.message : String(error),
      );
    }
  });
}
`;
}
