import { readFile } from 'node:fs/promises';
import { VisualRegressionError } from '../errors.js';

/**
 * Next.js prerender-manifest reading (plan §6.1–6.2). Supported shape: an
 * object with numeric `version` 3 or 4 and an object `routes` map. Anything
 * else fails closed, including unknown versions.
 */

function unsupported(manifestPath: string, reason: string, cause?: unknown): VisualRegressionError {
  return new VisualRegressionError(
    'PRERENDER_MANIFEST_UNSUPPORTED',
    `Unsupported prerender manifest at ${manifestPath}: ${reason}.`,
    { context: { path: manifestPath }, cause },
  );
}

export async function readPrerenderManifestRoutes(manifestPath: string): Promise<string[]> {
  let raw: string;
  try {
    raw = await readFile(manifestPath, 'utf8');
  } catch (error) {
    const notFound = (error as NodeJS.ErrnoException).code === 'ENOENT';
    throw new VisualRegressionError(
      'PRERENDER_MANIFEST_NOT_FOUND',
      `Prerender manifest ${notFound ? 'not found' : 'not readable'} at ${manifestPath}. ` +
        'It is generated by a completed production build; run the configured build command first.',
      { context: { path: manifestPath }, cause: error },
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw unsupported(manifestPath, 'file is not valid JSON', error);
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw unsupported(manifestPath, 'expected a JSON object');
  }
  const manifest = parsed as Record<string, unknown>;
  const version = manifest['version'];
  if (version !== 3 && version !== 4) {
    throw unsupported(manifestPath, `unknown manifest version ${JSON.stringify(version)}`);
  }
  const routes = manifest['routes'];
  if (routes === null || typeof routes !== 'object' || Array.isArray(routes)) {
    throw unsupported(manifestPath, 'missing or non-object "routes" map');
  }
  return Object.keys(routes as Record<string, unknown>);
}
